export enum TransactionTypeEnum {
  COMPLETED_MISSION = 'COMPLETED_MISSION',
  BOUGHT_PACKAGE_CLOVER = 'BOUGHT_PACKAGE_CLOVER',
  BOUGHT_THEME = 'BOUGHT_THEME',
  ADJUST_CLOVER = 'ADJUST_CLOVER',
  SUBSCRIBED = 'SUBSCRIBED',
}
