export enum LangEnum {
  vietnamese = 'vi',
  english = 'en',
  spanish = 'es',
  portuguese = 'pt',
  hindi = 'hi',
  french = 'fr',
  russian = 'ru',
  german = 'de',
  italian = 'it',
  korean = 'ko',
  japanese = 'ja',
  arabic = 'ar',
  afrikaans = 'af',
  urdu = 'ur',
  hebrew = 'he',
  chinese = 'zh',
  turkish = 'tr',
  indonesian = 'in',
  dutch = 'nl',
}

export enum TimeZoneEnum {
  vi = 'Asia/Ho_Chi_Minh',
  en = 'America/New_York',
  es = 'Europe/Madrid',
  pt = 'America/Sao_Paulo',
  hi = 'Asia/Kolkata',
  fr = 'Europe/Paris',
  ru = 'Europe/Moscow',
  de = 'Europe/Berlin',
  it = 'Europe/Rome',
  ko = 'Asia/Seoul',
  ja = 'Asia/Tokyo',
  ar = 'Asia/Dubai',
  af = 'Africa/Johannesburg',
  ur = 'Asia/Kolkata',
  he = 'Asia/Jerusalem',
  zh = 'Asia/Shanghai',
  tr = 'Europe/Istanbul',
  in = 'Asia/Jakarta',
  nl = 'Europe/Amsterdam',
}

export const TimeZoneList = [
  'Asia/Ho_Chi_Minh',
  'America/New_York',
  'Europe/Madrid',
  'America/Sao_Paulo',
  'Asia/Kolkata',
  'Europe/Paris',
  'Europe/Moscow',
  'Europe/Berlin',
  'Europe/Rome',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Asia/Dubai',
  'Africa/Johannesburg',
  'Asia/Kolkata',
  'Asia/Jerusalem',
  'Asia/Shanghai',
  'Europe/Istanbul',
  'Asia/Jakarta',
  'Europe/Amsterdam',
];
