export enum StatisticLocked {
  MOOD_FLOW = 'MOOD_FLOW',
  MOOD_BAR = 'MOOD_BAR',
  YEAR_IN_BEANS = 'YEAR_IN_BEANS',
  FREQUENTLY_RECORDED = 'FREQUENTLY_RECORDED',
  BEST_WORST = 'BEST_WORST',
  ICON_DEEP_DIVE = 'ICON_DEEP_DIVE',
  SLEEP_ANALYSIS = 'SLEEP_ANALYSIS',
  EXERCISE_ANALYSIS = 'EXERCISE_ANALYSIS',
  FAVORITE_EXERCISE = 'FAVORITE_EXERCISE',
  MENSTRUAL_ANALYSIS = 'MENSTRUAL_ANALYSIS',
}
