export const ONE_MINUTE_MILLISECONDS = 60 * 1000;
export const ONE_HOUR_MILLISECONDS = 60 * ONE_MINUTE_MILLISECONDS;
export const SIX_HOUR_MILLISECONDS = 6 * ONE_HOUR_MILLISECONDS;
export const EIGHT_HOUR_MILLISECONDS = 8 * ONE_HOUR_MILLISECONDS;

export const ONE_SECOND_MILLISECONDS = 1000;

export const ONE_DAY_MILLISECONDS = 24 * ONE_HOUR_MILLISECONDS;

export const SEVEN_DAY_MILLISECONDS = 7 * ONE_DAY_MILLISECONDS;

export const ONE_MONTH_MILLISECONDS = 30 * ONE_DAY_MILLISECONDS;

export const ONE_YEAR_MILLISECONDS = 365 * ONE_DAY_MILLISECONDS;
